array (
  'jpg' => 'image/jpeg',
  'bmp' => 'image/bmp',
  'ico' => 'image/x-icon',
  'gif' => 'image/gif',
  'png' => 'image/png',
  'bin' => 'application/octet-stream',
  'js' => 'application/javascript',
  'css' => 'text/css',
  'html' => 'text/html',
  'xml' => 'text/xml',
  'tar' => 'application/x-tar',
  'ppt' => 'application/vnd.ms-powerpoint',
  'pdf' => 'application/pdf',
  'swf' => 'application/x-shockwave-flash',
  'zip' => 'application/x-zip-compressed',
)